---
global:
  pattern: multicloud-gitops-intel-sgx

  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic

main:
  clusterGroupName: hub

  multiSourceConfig:
    enabled: true
