---
global:
  pattern: multicloud-gitops-intel-sgx
  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic
  images:
    intelDevicePlugins: registry.connect.redhat.com/intel/intel-sgx-plugin@sha256:1b89401a69bf664473b96fced1ded89551397b3b66e37a7a1b92d33bd3baccad
    intelDevicePluginsInit: registry.connect.redhat.com/intel/intel-sgx-initcontainer@sha256:656aba8b1958e50ac3d0cc8eb3a547eee1c623e934dfd2815f118acf79dc5fec
    nodeFeatureDiscovery: quay.io/openshift/origin-node-feature-discovery:4.13
main:
  clusterGroupName: hub
  multiSourceConfig:
    enabled: true
