---
global:
  openshift: true
  localClusterDomain: apps.foo.cluster.com

vault:
  injector:
    enabled: false
  ui:
    enabled: true
  server:
    extraEnvironmentVars:
      VAULT_CACERT: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
      VAULT_ADDR: https://vault.vault.svc.cluster.local:8200

    # Enable secured server container with Intel SGX (Intel Software Guard Extensions)
    sgx: true
    # TOMEK: SGX SHOULD BE DISABLED BY DEFAULT
    # sgx: false

    # TOMEK: MOVE IT TO OTHER PLACE AND ADD CONDITION IF SGX==true THEN....?
    resources:
      limits:
        sgx.intel.com/epc: 1Gi
      requests:
        sgx.intel.com/epc: 1Gi

    # TOMEK: MOVE IT TO OTHER PLACE AND ADD CONDITION IF SGX==true THEN....?
    statefulSet:
      securityContext:
        container:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            seccompProfile:
              type: RuntimeDefault
        pod:
          fsGroup: 107
          runAsGroup: 107
          runAsUser: 100

    standalone:
      config: |
        ui = true
        disable_mlock = true
        listener "tcp" {
          address = "[::]:8200"
          cluster_address = "[::]:8201"
          tls_cert_file = "/vault/userconfig/vault-secret/tls.crt"
          tls_key_file = "/vault/userconfig/vault-secret/tls.key"
        }
        storage "file" {
          path = "/vault/data"
        }

    # These are automatically mounted in /vault/userconfig/<name>
    extraVolumes:
    - type: secret
      name: vault-secret
    # TOMEK: TODEL BELOW ONE BECAUSE LOOKS LIKE IT IS NOT NEEDED
    # - type: configMap
    #   name: config

    service:
      enabled: true
      nonha:
        annotations:
          service.beta.openshift.io/serving-cert-secret-name: vault-secret
      internal:
        annotations:
          service.beta.openshift.io/serving-cert-secret-name: vault-secret-internal
    route:
      host: null
      enabled: true
      tls:
        # We cannot use passthrough because you'd be talking to
        # https://vault-vault.apps.mcg-hub.blueprints.rhecoeng.com but you'd
        # get vault.vault.svc/vault.vault.svc.cluster.local
        termination: "reencrypt"
    image:
      repository: "docker.io/seahorse910/sgx-gramine"
      tag: "rh-vault-1.15.3-ubi-sgx-gramine-loaderuid-vault107-threads512-vol"

    readinessProbe:
      enabled: false
