apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: openshift-operators
  namespace: multicloud-gitops-intel-sgx-hub
spec:
  description: Pattern openshift-operators
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'
status: {}
