# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

# These overrides are appropriate defaults for deploying this chart on OpenShift

global:
  openshift: true

injector:
  image:
    repository: "registry.connect.redhat.com/hashicorp/vault-k8s"
    tag: "1.3.1-ubi"

  agentImage:
    repository: "registry.connect.redhat.com/hashicorp/vault"
    tag: "1.15.2-ubi"

server:
  image:
    # repository: "registry.connect.redhat.com/hashicorp/vault"
    # tag: "1.15.2-ubi"
    repository: "docker.io/seahorse910/sgx-gramine"
    tag: "rh-vault-1.15.3-ubi-sgx-gramine-loaderuid-vault107-threads512-vol"

    # FOR TESTS CHANGE IMAGE PULL POLICY:
    pullPolicy: Always

  # # Enable secured server container with Intel SGX (Intel Software Guard Extensions)
  # sgx: true
  # # TOMEK: SGX SHOULD BE DISABLED BY DEFAULT
  # # sgx: false

  readinessProbe:
    path: "/v1/sys/health?uninitcode=204"
