apiVersion: batch/v1
kind: Job
metadata:
  name: hello-world-sgx
spec:
  parallelism: 1
  completions: 1
  activeDeadlineSeconds: 1800
  backoffLimit: 6
  template:
    metadata:
      name: hello-world-sgx
    spec:
      containers:
      - name: python
        image: seahorse911/python-hello-world:gramine
        env:
          - name: LC_ALL
            value: C.utf8
          - name: LANG
            value: C.utf8
        resources:
          requests:
            sgx.intel.com/epc: "1Gi"
          limits:
            sgx.intel.com/epc: "1Gi"
      restartPolicy: OnFailure
