{{- if .Values.vault.server.sgx }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nonroot-v2-scc-rolebinding
  namespace: vault
subjects:
  - kind: ServiceAccount
    name: vault
    namespace: vault
roleRef:
  kind: ClusterRole
  name: nonroot-v2-scc-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
