{{- if .Values.vault.server.sgx }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-vault-0
  namespace: vault
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # TOMEK: LOOKS LIKE THE BELOW IS NOT NEEDED BECAUSE DEFAUTL STORAGE CLASS SHOULD BE SET UP AND PICKED UP BY THIS PVC
  # storageClassName: ocs-storagecluster-cephfs
{{- end }}
