{{- if .Values.vault.server.sgx }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-vault-0
  namespace: vault
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
{{- end }}
